### ISSUE TITLE
publisher panic

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#466]
<pre>I'm seeing this panic once in a while on my prod server. Noting here so I can come back
to it later.

2014/06/30 01:13:21 http: panic serving 195.154.235.104:58749: runtime error: invalid
memory address or nil pointer dereference
goroutine 999 [running]:
net/http.func�011()
        /home/mpl/gotip/src/pkg/net/http/server.go:1102 +0xd8
runtime.panic(0xa18f80, 0x10e3168)
        /home/mpl/gotip/src/pkg/runtime/panic.c:248 +0x18d
main.(*publishRequest).serveSubjectTemplate(0xc2086a6000)
        /home/mpl/gocode/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/app/publisher/main.go:636 +0x434
main.(*publishRequest).serveHTTP(0xc2086a6000)
        /home/mpl/gocode/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/app/publisher/main.go:499 +0x780
main.(*publishHandler).ServeHTTP(0xc2087d0820, 0x7f4d648a1790, 0xc208880000,
0xc2087dd930)
        /home/mpl/gocode/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/app/publisher/main.go:285 +0x346
net/http.(*ServeMux).ServeHTTP(0xc208838330, 0x7f4d648a1790, 0xc208880000, 0xc2087dd930)
        /home/mpl/gotip/src/pkg/net/http/server.go:1519 +0x17f
camlistore.org/pkg/webserver.(*Server).ServeHTTP(0xc20883c0f0, 0x7f4d648a1790,
0xc208880000, 0xc2087dd930)
        /home/mpl/gocode/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/webserver/webserver.go:103 +0x2a3
net/http.serverHandler.ServeHTTP(0xc208753740, 0x7f4d648a1790, 0xc208880000,
0xc2087dd930)
        /home/mpl/gotip/src/pkg/net/http/server.go:1681 +0x19e
net/http.(*conn).serve(0xc2081b8000)
        /home/mpl/gotip/src/pkg/net/http/server.go:1182 +0x9fe
created by net/http.(*Server).Serve
        /home/mpl/gotip/src/pkg/net/http/server.go:1729 +0x2f6
2014/06/30 01:13:21 http: proxy error: EOF</pre>

**Comment by mpl** [comment]
That panic trace is now useless since the publisher code has changed quite a lot in the meantime.
I think I fixed this while working on the publisher anyway.
And if not, easy to reopen when needed.
