### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#563]
```
panic: send on closed channel

goroutine 53 [running]:
camlistore.org/pkg/search.(*wsHub).run(0xc208d34180)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath/src/camlistore.org/pkg/search/websocket.go:85 +0x685
created by camlistore.org/pkg/search.NewHandler
        /home/bradfitz/src/camlistore.org/tmp/build-gopath/src/camlistore.org/pkg/search/handler.go:89 +0x341

goroutine 1 [chan send (nil chan)]:
main.Main(0x0, 0x0)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath/src/camlistore.org/server/camlistored/camlistored.go:415 +0x131a
main.main()
        /home/bradfitz/src/camlistore.org/tmp/build-gopath/src/camlistore.org/server/camlistored/camlistored.go:317 +0x30

goroutine 51 [chan receive]:
main.handleSignals(0xc2088c8120)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath/src/camlistore.org/server/camlistored/camlistored.go:244 +0x294
created by main.Main
        /home/bradfitz/src/camlistore.org/tmp/build-gopath/src/camlistore.org/server/camlistored/camlistored.go:340 +0x67b

goroutine 52 [chan receive]:
camlistore.org/pkg/server.(*SyncHandler).runSync(0xc20850ab00, 0xe88800, 0x4, 0xc209100000, 0x0)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath/src/camlistore.org/pkg/server/sync.go:514 +0x43f
camlistore.org/pkg/server.(*SyncHandler).syncLoop(0xc20850ab00)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath/src/camlistore.org/pkg/server/sync.go:530 +0xc3
created by camlistore.org/pkg/server.newSyncFromConfig
        /home/bradfitz/src/camlistore.org/tmp/build-gopath/src/camlistore.org/pkg/server/sync.go:188 +0xa10

goroutine 50 [syscall]:
os/signal.loop()
        /home/bradfitz/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /home/bradfitz/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 49 [syscall, locked to thread]:
runtime.goexit()
        /home/bradfitz/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by bradfitz** [comment]
At rev 3648550b9f
