### ISSUE TITLE
camput: endless loop with no progress

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#662]
After uploading once, running this command subsequently usually gets into this loop:

```
ward5k:camlistore.org bradfitz$ devcam -nobuild  put file -filenodes website
2015/12/29 13:48:10 done statting:
2015/12/29 13:48:10 FILES: Total: {files:116 bytes:1187612} Skipped: {files:6 bytes:70688} Uploaded: {files:0 bytes:0}  BLOBS: [uploadRequests=[blobs=0 bytes=0] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: 
2015/12/29 13:48:10 done checking stat cache
sha1-48fcd905861e858c251b58ae2d3e374501a94f54
sha1-3513835f295c101300bcd811d009a7254254b4bb
sha1-599139714cc7027d5b8ee85ffb68fd9885caf57d
sha1-202c5b701ee7e99b4dcd5c393b1d2ef1fa75272b
sha1-bb4d8fab5b79b89e75febc79d94e75eaa6eecdd3
sha1-d03114d8e49a1f126690480477d3bc3b46555675
sha1-6262143d5cca9896807157df9830111d07d39587
sha1-3ea8cc4715a046d5466a08abfeffd19ec68bd8e8
sha1-f4e63b972f0b9971ebed937280d6d0cb3284b868
sha1-2560c18c8d1839bf0b20b0b2f2d38c323290bbe4
2015/12/29 13:48:10 done with all uploads.
2015/12/29 13:48:11 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:11 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:12 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:12 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:13 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:13 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:14 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:14 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:15 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:15 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:16 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:16 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:17 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
2015/12/29 13:48:17 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:11 bytes:20695}  BLOBS: [uploadRequests=[blobs=32 bytes=31881] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.9~
```

Notice it says "done with all uploads" (which should be followed by the `close(dirUpload)` in `cmd/camput/files.go`) but then we never see this error message:

```go
    dirUpload := chanworker.NewWorker(dirUploadWorkers, func(el interface{}, ok bool) {
           if !ok {
              log.Printf("done uploading directories - done with all uploads.")
              uploadsdonec <- true
              return
```

/cc @mpl

**Comment by bradfitz** [comment]
It's getting stuck in `uploadNode` of a directory.

Note the line `2015/12/29 14:00:12 dirUpload: pre-upload of website/blobserver-example/root/sha1/91` below:

```
2015/12/29 14:00:12 dirUpload(*main.node, true) ...
2015/12/29 14:00:12 dirUpload: pre-upload of website/containers/demoblobserver
2015/12/29 14:00:12 dirUpload: post-upload of website/containers/demoblobserver (err=<nil>)
2015/12/29 14:00:12 dirUpload: pre-send
2015/12/29 14:00:12 dirUploaded: post-send
2015/12/29 14:00:12 dirUpload(*main.node, true) ...
2015/12/29 14:00:12 dirUpload: pre-upload of website/containers/git
2015/12/29 14:00:12 dirUpload: post-upload of website/blobserver-example/root/sha1/10 (err=<nil>)
2015/12/29 14:00:12 dirUpload: pre-send
2015/12/29 14:00:12 dirUploaded: post-send
2015/12/29 14:00:12 dirUpload(*main.node, true) ...
2015/12/29 14:00:12 dirUpload: pre-upload of website/containers
2015/12/29 14:00:12 done checking stat cache
sha1-3513835f295c101300bcd811d009a7254254b4bb
sha1-48fcd905861e858c251b58ae2d3e374501a94f54
sha1-599139714cc7027d5b8ee85ffb68fd9885caf57d
sha1-202c5b701ee7e99b4dcd5c393b1d2ef1fa75272b
sha1-bb4d8fab5b79b89e75febc79d94e75eaa6eecdd3
sha1-f4e63b972f0b9971ebed937280d6d0cb3284b868
2015/12/29 14:00:12 dirUpload: post-upload of website/containers/git (err=<nil>)
2015/12/29 14:00:12 dirUpload: pre-send
2015/12/29 14:00:12 dirUploaded: post-send
2015/12/29 14:00:12 dirUpload(*main.node, true) ...
2015/12/29 14:00:12 dirUpload: pre-upload of website/blobserver-example/root/sha1
2015/12/29 14:00:12 dirUpload: post-upload of website/containers (err=<nil>)
2015/12/29 14:00:12 dirUpload: pre-send
2015/12/29 14:00:12 dirUploaded: post-send
2015/12/29 14:00:12 dirUpload(*main.node, true) ...
2015/12/29 14:00:12 dirUpload: pre-upload of website/blobserver-example/root/sha1/91
sha1-d03114d8e49a1f126690480477d3bc3b46555675
sha1-3ea8cc4715a046d5466a08abfeffd19ec68bd8e8
sha1-2560c18c8d1839bf0b20b0b2f2d38c323290bbe4
sha1-6262143d5cca9896807157df9830111d07d39587
2015/12/29 14:00:12 done with all uploads.
2015/12/29 14:00:12 closed dirUpload
2015/12/29 14:00:12 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
2015/12/29 14:00:13 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
2015/12/29 14:00:13 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
2015/12/29 14:00:14 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
2015/12/29 14:00:14 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
2015/12/29 14:00:15 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
2015/12/29 14:00:15 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
2015/12/29 14:00:16 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
2015/12/29 14:00:16 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
2015/12/29 14:00:17 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
2015/12/29 14:00:17 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
2015/12/29 14:00:18 FILES: Total: {files:116 bytes:1187612} Skipped: {files:84 bytes:1166917} Uploaded: {files:14 bytes:20695}  BLOBS: [uploadRequests=[blobs=38 bytes=33520] uploads=[blobs=0 bytes=0]] Digested: 0 last upload: website/content/docs/release/0.8~
```

**Comment by bradfitz** [comment]
Putting a cached directory is getting suck on waiting for the static-set's cached value, which never arrives:

```
goroutine 13 [semacquire]:
sync.runtime_Syncsemacquire(0xc8202e4a50)
	/Users/bradfitz/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc8202e4a40)
	/Users/bradfitz/go/src/sync/cond.go:63 +0x9b
main.(*node).PutResult(0xc8202e4a00, 0x0, 0x0, 0x0)
	/Users/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/cmd/camput/files.go:853 +0xb8
main.(*node).directoryStaticSet(0xc8202e48c0, 0x1, 0x0, 0x0)
	/Users/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/cmd/camput/files.go:378 +0xb4
main.(*Uploader).uploadNode(0xc82012bc70, 0xc8202e48c0, 0xc820373ea8, 0x0, 0x0)
	/Users/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/cmd/camput/files.go:412 +0xc62
main.(*TreeUpload).run.func4(0x7d3bc0, 0xc8202e48c0, 0xc820373f01)
	/Users/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/cmd/camput/files.go:1043 +0x2f8
camlistore.org/internal/chanworker.(*chanWorker).work(0xc8202bcb40)
	/Users/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/internal/chanworker/chanworker.go:117 +0xc0
created by camlistore.org/internal/chanworker.NewWorker
	/Users/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/internal/chanworker/chanworker.go:74 +0x29c
```

**Comment by bradfitz** [comment]
And it works if you change the chanworker pool size to -1 (unlimited), which isn't a real fix.

We're deadlocking because things are happening in the wrong order. We get blocked with 3 goroutines (the `dirUploadWorkers` const value) waiting forever for events which will never happen, because they also require `dirUploadWorkers` goroutines)
