### ISSUE TITLE
corpus deadlock

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#709]
Deadlock in corpus makes Camlistore unusable since ~February:

Backtrace: https://gist.github.com/bradfitz/585c4e1616736dd4d69774ac559b0a69

/cc @mpl

**Comment by bradfitz** [comment]
https://twitter.com/bradfitz/status/723235366874943488 and ...

```
2016/04/21 12:29:47 Available on https://camlihouse.bradfitz.com/ui/
panic: already RLocked

goroutine 384 [running]:
panic(0xc219a0, 0xc85cf6d890)
        /home/bradfitz/go/src/runtime/panic.go:500 +0x18c
camlistore.org/pkg/index.(*Corpus).RLock(0xc8205b1200, 0x14545c0, 0xc863a841b0)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/index/corpus.go:125 +0xdd
camlistore.org/pkg/index.(*Corpus).GetBlobMeta(0xc8205b1200, 0x14545c0, 0xc863a841b0, 0x1453400, 0xc830251960, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/index/corpus.go:909 +0x8d
camlistore.org/pkg/index.(*Index).GetBlobMeta(0xc8208be2d0, 0x14545c0, 0xc863a841b0, 0x1453400, 0xc830251960, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/index/index.go:774 +0xb0
camlistore.org/pkg/search.(*DescribeRequest).describeReally(0xc857bf20c0, 0x14545c0, 0xc863a841b0, 0x1453400, 0xc830251960, 0x1)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/search/describe.go:689 +0x73
camlistore.org/pkg/search.(*DescribeRequest).Describe.func1(0xc857bf20c0, 0x14545c0, 0xc863a841b0, 0x1453400, 0xc830251960, 0x1)
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/search/describe.go:585 +0x84
created by camlistore.org/pkg/search.(*DescribeRequest).Describe
        /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/search/describe.go:586 +0x1db
```
