### ISSUE TITLE
mysql database hang

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#782]
My index hung.

This goroutine looks odd (two minutes hung so far in a mysql query):

```
goroutine 1710670 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f37a0398848, 0x72, 0xc4208b7000)
	/home/bradfitz/go/src/runtime/netpoll.go:160 +0x4f
net.(*pollDesc).wait(0xc4620061b0, 0x72, 0xc469259648, 0xc420010180)
	/home/bradfitz/go/src/net/fd_poll_runtime.go:73 +0x2e
net.(*pollDesc).waitRead(0xc4620061b0, 0x142d1e0, 0xc420010180)
	/home/bradfitz/go/src/net/fd_poll_runtime.go:78 +0x2a
net.(*netFD).Read(0xc462006150, 0xc4208b7000, 0x1000, 0x1000, 0x0, 0x142d1e0, 0xc420010180)
	/home/bradfitz/go/src/net/fd_unix.go:212 +0x183
net.(*conn).Read(0xc4561c6738, 0xc4208b7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/bradfitz/go/src/net/net.go:173 +0x63
camlistore.org/vendor/github.com/go-sql-driver/mysql.(*buffer).fill(0xc461e05180, 0x4, 0x0, 0xfec)
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/go-sql-driver/mysql/buffer.go:55 +0xe3
camlistore.org/vendor/github.com/go-sql-driver/mysql.(*buffer).readNext(0xc461e05180, 0x4, 0xc469f32d80, 0x0, 0x0, 0xc4561c6738, 0x2)
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/go-sql-driver/mysql/buffer.go:76 +0xa3
camlistore.org/vendor/github.com/go-sql-driver/mysql.(*mysqlConn).readPacket(0xc4622cc0a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/go-sql-driver/mysql/packets.go:28 +0x3c
camlistore.org/vendor/github.com/go-sql-driver/mysql.(*mysqlConn).readResultSetHeaderPacket(0xc4622cc0a0, 0xc46324acc0, 0x2, 0x2)
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/go-sql-driver/mysql/packets.go:459 +0x25
camlistore.org/vendor/github.com/go-sql-driver/mysql.(*mysqlStmt).Exec(0xc44bc46660, 0xc46324acc0, 0x2, 0x2, 0xc46324acc0, 0x2, 0x2, 0x0)
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/go-sql-driver/mysql/statement.go:54 +0x8c
database/sql.resultFromStatement(0x142eca0, 0xc462092380, 0x1432820, 0xc44bc46660, 0xc469259bb8, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
	/home/bradfitz/go/src/database/sql/sql.go:1497 +0x1be
database/sql.(*Tx).Exec(0xc4622d21e0, 0xc461f77a80, 0x32, 0xc469259bb8, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
	/home/bradfitz/go/src/database/sql/sql.go:1394 +0x2b5
camlistore.org/pkg/sorted/sqlkv.(*batchTx).Set(0xc46324ac80, 0xc461460d00, 0x39, 0xc469f32bb0, 0x10)
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/sorted/sqlkv/sqlkv.go:119 +0x512
camlistore.org/pkg/index.(*Index).commit(0xc42008a750, 0xc46324a420, 0x0, 0x0)
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/index/receive.go:276 +0x134
camlistore.org/pkg/index.(*Index).ReceiveBlob(0xc42008a750, 0x1431920, 0xc463988180, 0x1428f60, 0xc4639883c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/index/receive.go:245 +0x599
camlistore.org/pkg/blobserver.receive(0x14266a0, 0xc42008a750, 0x1431920, 0xc463988180, 0x1428f60, 0xc4639883c0, 0xc46bbb0800, 0x413f3e, 0x30, 0xce1480, ...)
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/receive.go:50 +0xc3
camlistore.org/pkg/blobserver.ReceiveNoHash(0x14266a0, 0xc42008a750, 0x1431920, 0xc463988180, 0x14262a0, 0xc44d57c990, 0xc4692d22e8, 0x0, 0x0, 0x408753, ...)
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/receive.go:42 +0x65
camlistore.org/pkg/blobserver/replica.(*replicaStorage).ReceiveBlob.func1(0x1, 0x14266a0, 0xc42008a750)
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/replica/replica.go:210 +0x118
created by camlistore.org/pkg/blobserver/replica.(*replicaStorage).ReceiveBlob
	/home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/replica/replica.go:214 +0x211
```

The rest: https://gist.github.com/bradfitz/fc2f142d003df1bfd1614f9cf3e0262e

/cc @mpl

**Comment by bradfitz** [comment]
From the MySQL side, I'm also seeing trivial queries taking forever:

```
mysql> show processlist;
+--------+----------+-----------------+------+---------+------+----------+----------------------------------------------------+
| Id     | User     | Host            | db   | Command | Time | State    | Info                                               |
+--------+----------+-----------------+------+---------+------+----------+----------------------------------------------------+
| 422499 | bradfitz | localhost:35532 | NULL | Sleep   |  237 |          | NULL                                               |
| 422502 | bradfitz | localhost:35570 | NULL | Sleep   |  134 |          | NULL                                               |
| 422510 | bradfitz | localhost:35604 | NULL | Sleep   |  186 |          | NULL                                               |
| 422511 | bradfitz | localhost:35612 | NULL | Sleep   |   83 |          | NULL                                               |
| 422512 | bradfitz | localhost:35618 | NULL | Sleep   |   32 |          | NULL                                               |
| 422516 | bradfitz | localhost:35626 | NULL | Sleep   |   32 |          | NULL                                               |
| 422517 | root     | localhost       | NULL | Query   |    0 | starting | show processlist                                   |
| 422518 | bradfitz | localhost:35634 | NULL | Execute |   32 | update   | REPLACE INTO bradcamlihv.rows (k, v) VALUES (?, ?) |
+--------+----------+-----------------+------+---------+------+----------+----------------------------------------------------+
8 rows in set (0.00 sec)
```

So maybe it's MySQL's fault.

It's on an SSD, and there's free disk space.

**Comment by bradfitz** [comment]
Can't reproduce with same queries by hand (with the mysql client).

Maybe it's a Go 1.6 vs Go tip issue.

**Comment by mpl** [comment]
if it is (a Go tip issue), gopherjs does not work with go tip either atm anyway.

**Comment by bradfitz** [comment]
I figured it out.

My MySQL scheme was old and had the wrong widths (only 256 bytes for the rows.k value). I then had a blob with a large title (longer than 256) trying to be inserted. It was passing the `sorted.CheckSizes(key, value)` check, but then it was failing on the last statement of:

```go
func (b *batchTx) Set(key, value string) {
        if b.err != nil {
                return
        }
        if err := sorted.CheckSizes(key, value); err != nil {
                if err == sorted.ErrKeyTooLarge {
                        b.err = fmt.Errorf("%v: %v", err, key)
                } else {
                        b.err = fmt.Errorf("%v: %v", err, value)
                }
                return
        }
        if b.kv.BatchSetFunc != nil {
                b.err = b.kv.BatchSetFunc(b.tx, key, value)
                return
        }
        _, b.err = b.tx.Exec(b.kv.sql("REPLACE INTO /*TPRE*/rows (k, v) VALUES (?, ?)"), key, value)
}
```

But when it sets b.err, everything thereafter ignores future mutations, but in commit batch,

```go
func (kv *KeyValue) CommitBatch(b sorted.BatchMutation) error {
        if kv.Gate != nil {
                defer kv.Gate.Done()
        }
        bt, ok := b.(*batchTx)
        if !ok {
                return fmt.Errorf("wrong BatchMutation type %T", b)
        }
        if bt.err != nil {
                return bt.err
        }
        return bt.tx.Commit()
}
```

... it returns bt.err, but keeps the transaction open, holding database locks.

We need to issue a rollback there.

We should have a test for this, too.

**Comment by mpl** [comment]
ouch, what a story. (and I thought we had devised a migration route when we did the key size change...)

**Comment by mpl** [comment]
I've just hit something related while restarting my camlistored (with mysql):

2016/06/05 23:50:07 Caught panic installer handlers: error instantiating handler for prefix "/my-search/", type "search": error slurping index to memory: bogus claim row: "claim|sha1-00d329f139b347290c9a7cabb52963f2593b3fe3|93A440E7F2AEB2C1|2016-05-13T14:23:34.736580926Z|sha1-60e2682a16bfaa1b39ec051c5ea893f8df4bd576" -> "set-attribute|content|RT+%40searls%3A+%F0%9F%92%AB+Computer+terms%3A%0Acloud+%3D+servers%0Aalgorithm+%3D+code%0Aapp+%3D+code+w%2Fan+icon%0Areason+about+%3D+understand%0Aisomorphic+%3D+reused%0Atechnical%E2%80%A6|sha1-47c8fd0632994d6ec0617582693f608d778aee"

Because of the old schema size, the signer ref (sha1-47c8fd0632994d6ec0617582693f608d778aee) has been truncated (it's missing 2 bytes). Sneaky.

I forgot about that issue because I thought you had already fixed it. On it.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6718

**Comment by mpl** [comment]
It turns out my problem is pretty different.

even though my mysql db schema is already at 22, and even after a reindex, I have the truncated entry above which leads to the failure. So I'll open another issue for it.
