### ISSUE TITLE
ExFAT on OSX 10.11.6 gives permission errors and reports existing dirs missing

### ISSUE THREAD

**Issue by cmpis** [camlistore/camlistore#841]
I have an external drive I wanted to setup a server for to do offline syncing from my local server to it. It's an SSD over USB 3 that's formatted with ExFAT.

I'm pretty sure this is OS X's fault, but I'm wondering if there isn't something we could do since I've been able to write/read correctly before.

```
2016/08/18 23:49:22 Starting camlistored version 2016-08-18-e321eb7+; Go go1.6.1 (darwin/amd64)
2016/08/18 23:49:22 Starting to listen on http://localhost:3180
2016/08/18 23:49:22 Caught panic installer handlers: error instantiating storage for prefix "/bs-loose/", type "filesystem": Storage root "/Volume/cmp-drive-3/camlistore/blobs/" doesn't exist
<snip>
       	/Users/cmp/Code/github/camlistore/tmp/build-gopath/src/camlistore.org/server/camlistored/camlistored.go:355 +0x29
Error parsing config: Caught panic: error instantiating storage for prefix "/bs-loose/", type "filesystem": Storage root "/Volume/cmp-drive-3/camlistore/blobs/" doesn't exist
```

```
/V/c/camlistore ❯❯❯ pwd
/Volumes/cmp-drive-3/camlistore
/V/c/camlistore ❯❯❯ ll
total 768
drwxrwxrwx  1 cmp  staff   128K Aug 18 23:48 blobs
drwxrwxrwx  1 cmp  staff   128K Aug 18 23:48 cache
drwxrwxrwx  1 cmp  staff   128K Aug 18 23:48 index.leveldb
/V/c/camlistore ❯❯❯
```

**Comment by cmpis** [comment]
Actually it doesn't seem to matter if it's ExFAT or not. Reformatted the external drive as OS X's default HFS (Journaled) and exactly the same errors happen. Folders/files that are there are being reported as missing and `camlistored` can't set it self up. 

More strange to me is this issue that camlistored is trying to `mkdir` `/Volumes` for some reason? Not sure why it'd be trying to create that folder and not go directly to where it needs to be because /Volumes is a special folder on OS X.

I also don't see any issues with permissions by looking at the files/folders. I tried to run `camlistored` in sudo as well to see that'd do anything. The errors change, but it still fails for similar reasons. 

I'm getting a bit lost trying to follow the handlers since they're registered dynamically.

Here's what I'm seeing:
```
~/C/g/camlistore ❯❯❯ camlistored -configfile cmp-drive-3-config.json
2016/08/19 20:32:04 Starting camlistored version 2016-08-18-e321eb7+; Go go1.6.1 (darwin/amd64)
2016/08/19 20:32:05 Starting to listen on http://localhost:3180
2016/08/19 20:32:05 Caught panic installer handlers: error instantiating storage for prefix "/index/", type "index": error from "leveldb" KeyValue: mkdir /Volume: permission denied
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
       	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
<snip>
       	/Users/cmp/Code/github/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/server/camlistored/camlistored.go:355 +0x29
Error parsing config: Caught panic: error instantiating storage for prefix "/index/", type "index": error from "leveldb" KeyValue: mkdir /Volume: permission denied
```

**Comment by tgulacsi** [comment]
Please share that configfile!

**Comment by cmpis** [comment]
# cmp-drive-3-config.json
```
{
  "auth": "localhost",
  "handlerConfig": true,
  "https": false,
  "listen": ":3180",
  "prefixes": {
    "/": {
      "handler": "root",
      "handlerArgs": {
        "blobRoot": "/bs-and-maybe-also-index/",
        "helpRoot": "/help/",
        "jsonSignRoot": "/sighelper/",
        "searchRoot": "/my-search/",
        "statusRoot": "/status/",
        "stealth": false
      }
    },
    "/bs-and-index/": {
      "handler": "storage-replica",
      "handlerArgs": {
        "backends": [
          "/bs/",
          "/index/"
        ]
      }
    },
    "/bs-and-maybe-also-index/": {
      "handler": "storage-cond",
      "handlerArgs": {
        "read": "/bs/",
        "write": {
          "else": "/bs/",
          "if": "isSchema",
          "then": "/bs-and-index/"
        }
      }
    },
    "/bs-loose/": {
      "handler": "storage-filesystem",
      "handlerArgs": {
        "path": "/Volume/cmp-drive-3/camlistore/blobs/"
      }
    },
    "/bs-packed/": {
      "handler": "storage-filesystem",
      "handlerArgs": {
        "path": "/Volume/cmp-drive-3/camlistore/blobs/packed"
      }
    },
    "/bs/": {
      "handler": "storage-blobpacked",
      "handlerArgs": {
        "largeBlobs": "/bs-packed/",
        "metaIndex": {
          "file": "/Volume/cmp-drive-3/camlistore/blobs/packed/packindex.leveldb",
          "type": "leveldb"
        },
        "smallBlobs": "/bs-loose/"
      }
    },
    "/cache/": {
      "handler": "storage-filesystem",
      "handlerArgs": {
        "path": "/Volume/cmp-drive-3/camlistore/blobs/cache"
      }
    },
    "/help/": {
      "handler": "help"
    },
    "/importer/": {
      "handler": "importer",
      "handlerArgs": {}
    },
    "/index/": {
      "handler": "storage-index",
      "handlerArgs": {
        "blobSource": "/bs/",
        "storage": {
          "file": "/Volume/cmp-drive-3/camlistore/index.leveldb",
          "type": "leveldb"
        }
      }
    },
    "/my-search/": {
      "handler": "search",
      "handlerArgs": {
        "index": "/index/",
        "owner": "sha1-f4d9c5aaeb661d4235df949e670405b9f27acadd",
        "slurpToMemory": true
      }
    },
    "/setup/": {
      "handler": "setup"
    },
    "/sighelper/": {
      "handler": "jsonsign",
      "handlerArgs": {
        "keyId": "372D5028",
        "publicKeyDest": "/bs-and-index/",
        "secretRing": "/Users/cmp/.config/camlistore/identity-secring.gpg"
      }
    },
    "/status/": {
      "handler": "status"
    },
    "/sync/": {
      "handler": "sync",
      "handlerArgs": {
        "from": "/bs/",
        "queue": {
          "file": "/Volume/cmp-drive-3/camlistore/blobs/sync-to-index-queue.leveldb",
          "type": "leveldb"
        },
        "to": "/index/"
      }
    },
    "/ui/": {
      "handler": "ui",
      "handlerArgs": {
        "cache": "/cache/",
        "scaledImage": {
          "file": "/Volume/cmp-drive-3/camlistore/blobs/thumbmeta.leveldb",
          "type": "leveldb"
        }
      }
    }
  }
}
```
