### ISSUE TITLE
website/camweb: do not e-mail when no smtp

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#860]
This happened when trying to test camweb in "semi-production" (trying to start it with cloudlaunch as well, but on another projectID):

	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: 2016/09/30 14:40:15 Failed to connect to SMTP server: dial tcp 127.0.0.1:25: getsockopt: connection refused
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: panic: runtime error: invalid memory address or nil pointer dereference
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]:         panic: runtime error: invalid memory address or nil pointer dereference
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x5aab86]
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: goroutine 1 [running]:
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: panic(0xb6a140, 0xc42000c050)
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]:         /home/mpl/go1/src/runtime/panic.go:500 +0x1a1
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: net/smtp.(*Client).hello(0x0, 0xc4201a8380, 0x6c)
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]:         /home/mpl/go1/src/net/smtp/smtp.go:79 +0x26
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: net/smtp.(*Client).Quit(0x0, 0x1, 0x1)
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]:         /home/mpl/go1/src/net/smtp/smtp.go:381 +0x2f
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: panic(0xb6a140, 0xc42000c050)
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]:         /home/mpl/go1/src/runtime/panic.go:458 +0x243
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: net/smtp.(*Client).hello(0x0, 0xc4201a8900, 0x57)
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]:         /home/mpl/go1/src/net/smtp/smtp.go:79 +0x26
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: net/smtp.(*Client).Mail(0x0, 0xc755f6, 0x16, 0x1, 0x1)
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]:         /home/mpl/go1/src/net/smtp/smtp.go:239 +0x40
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: main.sendStartingEmail()
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]:         /home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/website/camweb.go:703 +0x144
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: main.setProdFlags()
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]:         /home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/website/camweb.go:624 +0x391
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]: main.main()
	Sep 30 14:40:15 camweb.c.granivo-re.internal camweb[12227]:         /home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/website/camweb.go:773 +0x7a

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/8407
