### ISSUE TITLE
camlistore stops with exit code 2

### ISSUE THREAD

**Issue by IanLewis** [camlistore/camlistore#945]
I am having problems with my data which I think may be corrupted. camlistored got OOM killed at some point and after that wouldn't start up even though I added enough memory for it to run. It simply crashes with exit code 2 and no log messages.

I tried reindexing but it just exits with exit code 2.
```
2017/09/09 10:11:47 Starting camlistored version 2017-04-05-9e34d14ef5; Go go1.8.1 (linux/amd64)
2017/09/09 10:11:47 Starting to listen on http://localhost:3179
2017/09/09 10:11:47 Index wiped.
2017/09/09 10:11:47 Reindexing /index/ ...
2017/09/09 10:11:47 Rebuilding index...
2017/09/09 10:11:47 Reindexing at sha1-00000737a0f0c24e63641fd9e1117eb34904637e
2017/09/09 10:11:48 Reindexing at sha1-0065b3e49b9db57283c951f9f2b2268ae5f142f4
2017/09/09 10:11:49 Reindexing at sha1-00c7d219f197b169ecce97b57669fcb2e7ef1b80
...
2017/09/09 10:12:54 Reindexing at sha1-0b0d1e547161506fb5df640b098fdfc15ebc6215
2017/09/09 10:12:55 Reindexing at sha1-0b2600369ee104da14ed4f1ce1f01286de6ffb60
2017/09/09 10:12:56 Reindexing at sha1-0b3f4cc9d6715ecb4c03f83ad7f4d1a942fede0b
```
It stops at this point.

Any idea how I could fix or debug this?

**Comment by mpl** [comment]
thanks for the report.

I'll need to think about it some more before I can give any meaningful advice.

Just to clarify, are you saying that it exits in the same way whether you reindex or not, i.e. when you run with -reindex, you think it is done reindexing at the moment that it exits?

**Comment by mpl** [comment]
So the weird thing is I don't see any relevant part of the code that exits with 2.

Nevertheless, without any other idea for now, I'd start with prints in server/camlistored/camlistored.go . In particular, I'd check whether you exit before, during, or after,

    config.InstallHandlers

And if during, I'd pinpoint which handler is causing problem, in pkg/serverinit/serverinit.go, where we loop over all handlers: 

    for prefix, vei := range prefixes {

**Comment by IanLewis** [comment]
It happened with the index present. If I blew away the index I could start camlistored but no index (obviously). Running with -reindex would also cause the issue during reindexing. I don't believe it was finished indexing. I'm pretty sure I have a lot more blobs than were shown in the logs before it stopped.

I did a cursory look a while back and I didn't see anything exiting with code 2 either. That makes me feel like I'm still running into memory issues. I'll see if I can reproduce again.

* As an aside, what kind of memory usage is typical? I'm currently running it in a container which I give about 8.5Gb but I think that's probably not enough. Any tips on helping keep memory usage low?

**Comment by IanLewis** [comment]
I tried reindexing outside of a container so that it would more likely succeed. It was able to index a lot more blobs but it crashed with the following error. I guess I am missing some blobs or something :(

```
2017/09/10 04:27:53 Caught panic installer handlers: Error reindexing /index/: 30 blobs are still needed as dependencies
goroutine 1 [running]:
runtime/debug.Stack(0xc420056140, 0x2, 0xc424dd81c0)
        /opt/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /opt/go/src/runtime/debug/stack.go:16 +0x22
camlistore.org/pkg/serverinit.(*Config).InstallHandlers.func1(0xc4205e9c30)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:540 +0xa8
panic(0xed1f80, 0xc4251410b0)
        /opt/go/src/runtime/panic.go:489 +0x2cf
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc4208fce70, 0xc420614980, 0x10deb78, 0xb)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:308 +0x1a2
panic(0xed1f80, 0xc4251410b0)
        /opt/go/src/runtime/panic.go:489 +0x2cf
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc4208fccf0, 0xc420614980, 0x10e2047, 0xe)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:308 +0x1a2
panic(0xed1f80, 0xc4251410b0)
        /opt/go/src/runtime/panic.go:489 +0x2cf
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc4208fd170, 0xc420614980, 0x10d9a75, 0x7)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:308 +0x1a2
panic(0xed1f80, 0xc4251410b0)
        /opt/go/src/runtime/panic.go:489 +0x2cf
camlistore.org/pkg/serverinit.exitFailure(0x10ecb8c, 0x17, 0xc4205e8b40, 0x2, 0x2)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:277 +0xe8
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc420614980, 0x10d9a75, 0x7)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:329 +0x90f
camlistore.org/pkg/serverinit.(*handlerLoader).GetStorage(0xc420614980, 0x10d9a75, 0x7, 0x0, 0x1, 0xc4210783c0, 0x0)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:251 +0x43
camlistore.org/pkg/blobserver/replica.newFromConfig(0x1b46900, 0xc420614980, 0xc4208fc270, 0x7, 0xc420074bf0, 0x42af01, 0xc420056120)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/replica/replica.go:112 +0x24b
camlistore.org/pkg/blobserver.CreateStorage(0x10e40aa, 0x7, 0x1b46900, 0xc420614980, 0xc4208fc270, 0xe, 0x1, 0x2, 0x6c50000c80015a5)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/registry.go:111 +0xc3
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc420614980, 0x10e2047, 0xe)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:321 +0x22c
camlistore.org/pkg/serverinit.(*handlerLoader).GetStorage(0xc420614980, 0x10e2047, 0xe, 0x1b377e0, 0xc4208f1be0, 0x1b41ce0, 0xc4208f1bc0)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:251 +0x43
camlistore.org/pkg/jsonsign/signhandler.newJSONSignFromConfig(0x1b46900, 0xc420614980, 0xc4208d9f20, 0x8, 0xc420138b18, 0x42af01, 0xc4200560d0)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/jsonsign/signhandler/sig.go:109 +0x750
camlistore.org/pkg/blobserver.CreateHandler(0x10dbd91, 0x8, 0x1b46900, 0xc420614980, 0xc4208d9f20, 0xb, 0x0, 0x1, 0x70)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/registry.go:140 +0xc3
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc420614980, 0x10deb78, 0xb)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:370 +0xb71
camlistore.org/pkg/serverinit.(*handlerLoader).setupAll(0xc420614980)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:231 +0x9a
camlistore.org/pkg/serverinit.(*Config).InstallHandlers(0xc4208c5b40, 0x1b341e0, 0xc420614880, 0xc4208f14c0, 0x15, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:609 +0x4e8
main.Main(0x0, 0x0)
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/server/camlistored/camlistored.go:758 +0x569
main.main()
        /home/ianlewis/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/server/camlistored/camlistored.go:701 +0x33
Error parsing config: Caught panic: Error reindexing /index/: 30 blobs are still needed as dependencies
```

**Comment by mpl** [comment]
I don't know the size of your data, but 8.5GB usage seems like a lot.

On my "production" instance, the last time I reindexed, I had figures like this:

     2015/07/21 23:33:12 Corpus stats: 22.990 MiB mem: 124381 blobs (6.392 GiB) (36813 schema (3176 permanode, 3039 file (3012 image), ...)

and right now, /proc/pid/status is reporting a VmSize: 2136880 kB

But yeah, docker might be a factor too.

thanks for the stack trace, I'll try to have a look later today. Otherwise on monday.

**Comment by IanLewis** [comment]
I ran camlistore with recovery mode and it seems to have fixed my issue. It would be good if camlistore was a bit more graceful with problems like this but it doesn't seem as important.

BTW mine is currently as follows:
```
Corpus stats: 319.053 MiB mem: 762836 blobs (7.133 GiB) (674595 schema (17016 permanode, 4627 file (4577 image), ...)
```

BTW. It seems to use about 1GB in my setup.
```
/go # cat /proc/1/status
Name:	camlistored
State:	S (sleeping)
Tgid:	1
Ngid:	0
Pid:	1
PPid:	0
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	256
Groups:	0 1 2 3 4 6 10 11 20 26 27 
NStgid:	1
NSpid:	1
NSpgid:	1
NSsid:	1
VmPeak:	 1052304 kB
VmSize:	 1052304 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	 1025596 kB
VmRSS:	 1025596 kB
VmData:	 1028336 kB
VmStk:	     136 kB
VmExe:	   10260 kB
VmLib:	     544 kB
VmPTE:	    2064 kB
VmPMD:	      24 kB
VmSwap:	       0 kB
Threads:	42
SigQ:	0/52109
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	fffffffe7fc1feff
CapInh:	00000000a80425fb
CapPrm:	00000000a80425fb
CapEff:	00000000a80425fb
CapBnd:	00000000a80425fb
CapAmb:	0000000000000000
Seccomp:	0
Cpus_allowed:	3
Cpus_allowed_list:	0-1
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	13274
nonvoluntary_ctxt_switches:	77743
```

**Comment by mpl** [comment]
Hmm somehow I was convinced you had either already run in recovery mode or that I had already asked you to do so. I was probably confusing this issue with the thread about recovery on the mailing-list, sorry.

You're totally right that we should be better at diagnosing and treating errors. There's already some detection for times when -recovery is needed, but it's clearly not enough to catch your case.
If you do find a way to reliably reproduce your issue so we can work on catching it again in the future that would be great.

I'll close this issue in the meantime, but feel free to reopen it if needed.

On a side-note, it's interesting that we seem to have a similar amount of raw data, but you have way more indexed schemas, and therefore a corpus already an order of magnitude larger.
