### ISSUE TITLE
Failure trying to run canary branch

### ISSUE THREAD

**Issue by tjgillies** [camlistore/camlistore#970]
```
# camlistored
2017/10/25 03:45:06 Starting camlistored version 2017-10-18-21b1ee05e0; Go go1.9.1 (linux/amd64)
2017/10/25 03:45:06 Starting to listen on http://localhost:3179
2017/10/25 03:45:06 index: adding the missing keyShare rows...
2017/10/25 03:45:07 index: successfully added keyShare rows.
2017/10/25 03:45:07 Caught panic installer handlers: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc420072190, 0x2, 0xc422d3c000)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
camlistore.org/pkg/serverinit.(*Config).InstallHandlers.func1(0xc4216a7c68)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:542 +0xa8
panic(0xf5e0c0, 0x1c61130)
        /usr/local/go/src/runtime/panic.go:491 +0x283
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc42302c510, 0xc422e7de80, 0x10ea284, 0x7)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:308 +0x1a2
panic(0xf5e0c0, 0x1c61130)
        /usr/local/go/src/runtime/panic.go:491 +0x283
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc42302c150, 0xc422e7de80, 0x10ea25a, 0x7)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:308 +0x1a2
panic(0xf5e0c0, 0x1c61130)
        /usr/local/go/src/runtime/panic.go:491 +0x283
camlistore.org/pkg/blob.(*serialFetcher).Fetch(0xc42300e9c0, 0x1c24da0, 0xc420753980, 0x2d, 0x1c24da0, 0xc420753980, 0xc422e2e401, 0x1)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blob/fetcher.go:76 +0x85
camlistore.org/pkg/jsonsign.(*VerifyRequest).FindAndParsePublicKeyBlob(0xc4201da0c0, 0xc42300e900)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/jsonsign/verify.go:141 +0x62
camlistore.org/pkg/jsonsign.(*VerifyRequest).Verify(0xc4201da0c0, 0x2b1)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/jsonsign/verify.go:226 +0x160
camlistore.org/pkg/index.(*Index).populateClaim(0xc42302edc0, 0x1c25e20, 0xc42001a4a0, 0xc420310360, 0xc420310330, 0xc4216a6b60, 0x0, 0x0)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/index/receive.go:822 +0x271
camlistore.org/pkg/index.(*Index).addMissingKeyShare(0xc42302edc0, 0x7fb5ec95f6f8, 0xc422f1d620, 0x0, 0x0)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/index/index.go:358 +0x7eb
camlistore.org/pkg/index.newFromConfig(0x1c29a20, 0xc422e7de80, 0xc422ffbc80, 0x5, 0xc4201a9028, 0x42bd01, 0xc42011cee0)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/index/index.go:421 +0x3de
camlistore.org/pkg/blobserver.CreateStorage(0x10f1193, 0x5, 0x1c29a20, 0xc422e7de80, 0xc422ffbc80, 0x7, 0x0, 0x1, 0x1c1d260)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/registry.go:111 +0xc3
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc422e7de80, 0x10ea25a, 0x7)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:321 +0x25c
camlistore.org/pkg/serverinit.(*handlerLoader).GetHandler(0xc422e7de80, 0x10ea25a, 0x7, 0x1c16720, 0xc422f1d620, 0x1, 0x0)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:259 +0x43
camlistore.org/pkg/server.newShareFromConfig(0x1c29a20, 0xc422e7de80, 0xc422ffb590, 0x5, 0xc42006e640, 0x42bd01, 0xc42011c940)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/server/share.go:146 +0x35e
camlistore.org/pkg/blobserver.CreateHandler(0x10e8bbe, 0x5, 0x1c29a20, 0xc422e7de80, 0xc422ffb590, 0x7, 0x11, 0xc422e7de80, 0x1c1d260)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/registry.go:140 +0xc3
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc422e7de80, 0x10ea284, 0x7)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:370 +0xa9e
camlistore.org/pkg/serverinit.(*handlerLoader).setupAll(0xc422e7de80)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:231 +0x92
camlistore.org/pkg/serverinit.(*Config).InstallHandlers(0xc422f9b080, 0x1c17220, 0xc422e7dd00, 0xc42300ad80, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:611 +0xb7e
main.Main(0x0, 0x0)
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/server/camlistored/camlistored.go:759 +0x4dd
main.main()
        /root/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/server/camlistored/camlistored.go:702 +0x33
Error parsing config: Caught panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by lindner** [comment]
This is pretty old at this point.  Can you reproduce?
